// <auto-generated />
using System;
using HR_Dash.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR_Dash.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250818105708_SkiftRullandeSchemaNav")]
    partial class SkiftRullandeSchemaNav
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnstalldSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnstalldId")
                        .HasColumnType("int");

                    b.Property<int>("RullandeSchemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnstalldId");

                    b.HasIndex("RullandeSchemaId");

                    b.ToTable("AnstalldSchema");
                });

            modelBuilder.Entity("HR_Dash.Models.Ansokan", b =>
                {
                    b.Property<int>("AnsokanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnsokanId"));

                    b.Property<string>("AnsokanTyp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnstalldId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("AnsokanId");

                    b.HasIndex("AnstalldId");

                    b.ToTable("Ansokningar");
                });

            modelBuilder.Entity("HR_Dash.Models.Anstalld", b =>
                {
                    b.Property<int>("AnstalldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnstalldId"));

                    b.Property<string>("AnstalldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AnstallningDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avdelning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilBild")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnstalldId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Anstallda");
                });

            modelBuilder.Entity("HR_Dash.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HR_Dash.Models.Mote", b =>
                {
                    b.Property<int>("MoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoteId"));

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Plats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SlutTid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MoteId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Moten");
                });

            modelBuilder.Entity("HR_Dash.Models.MoteAnstalld", b =>
                {
                    b.Property<int>("MoteId")
                        .HasColumnType("int");

                    b.Property<int>("AnstalldId")
                        .HasColumnType("int");

                    b.HasKey("MoteId", "AnstalldId");

                    b.HasIndex("AnstalldId");

                    b.ToTable("MoteAnstallda");
                });

            modelBuilder.Entity("HR_Dash.Models.RullandeSchema", b =>
                {
                    b.Property<int>("IdSchema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSchema"));

                    b.Property<string>("MonsterString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamnSkift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkiftMinuter")
                        .HasColumnType("int");

                    b.Property<int>("SkiftTimmar")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTid")
                        .HasColumnType("time");

                    b.HasKey("IdSchema");

                    b.ToTable("RullandeScheman");
                });

            modelBuilder.Entity("HR_Dash.Models.Skift", b =>
                {
                    b.Property<int>("IdSkift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSkift"));

                    b.Property<int>("AnstalldId")
                        .HasColumnType("int");

                    b.Property<int?>("AnstalldSchemaId")
                        .HasColumnType("int");

                    b.Property<int?>("RullandeSchemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutTid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("datetime2");

                    b.HasKey("IdSkift");

                    b.HasIndex("AnstalldId");

                    b.HasIndex("AnstalldSchemaId");

                    b.HasIndex("RullandeSchemaId");

                    b.ToTable("Skift");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AnstalldSchema", b =>
                {
                    b.HasOne("HR_Dash.Models.Anstalld", "Anstalld")
                        .WithMany()
                        .HasForeignKey("AnstalldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR_Dash.Models.RullandeSchema", "RullandeSchema")
                        .WithMany("Anstallda")
                        .HasForeignKey("RullandeSchemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anstalld");

                    b.Navigation("RullandeSchema");
                });

            modelBuilder.Entity("HR_Dash.Models.Ansokan", b =>
                {
                    b.HasOne("HR_Dash.Models.Anstalld", "Anstalld")
                        .WithMany("Ansokningar")
                        .HasForeignKey("AnstalldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anstalld");
                });

            modelBuilder.Entity("HR_Dash.Models.Anstalld", b =>
                {
                    b.HasOne("HR_Dash.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Anstalld")
                        .HasForeignKey("HR_Dash.Models.Anstalld", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("HR_Dash.Models.Mote", b =>
                {
                    b.HasOne("HR_Dash.Models.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HR_Dash.Models.MoteAnstalld", b =>
                {
                    b.HasOne("HR_Dash.Models.Anstalld", "Anstalld")
                        .WithMany()
                        .HasForeignKey("AnstalldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Dash.Models.Mote", "Mote")
                        .WithMany("MoteAnstallda")
                        .HasForeignKey("MoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anstalld");

                    b.Navigation("Mote");
                });

            modelBuilder.Entity("HR_Dash.Models.Skift", b =>
                {
                    b.HasOne("HR_Dash.Models.Anstalld", "Anstalld")
                        .WithMany("Skift")
                        .HasForeignKey("AnstalldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnstalldSchema", "AnstalldSchema")
                        .WithMany()
                        .HasForeignKey("AnstalldSchemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HR_Dash.Models.RullandeSchema", "RullandeSchema")
                        .WithMany()
                        .HasForeignKey("RullandeSchemaId");

                    b.Navigation("Anstalld");

                    b.Navigation("AnstalldSchema");

                    b.Navigation("RullandeSchema");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HR_Dash.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HR_Dash.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR_Dash.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HR_Dash.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HR_Dash.Models.Anstalld", b =>
                {
                    b.Navigation("Ansokningar");

                    b.Navigation("Skift");
                });

            modelBuilder.Entity("HR_Dash.Models.ApplicationUser", b =>
                {
                    b.Navigation("Anstalld");
                });

            modelBuilder.Entity("HR_Dash.Models.Mote", b =>
                {
                    b.Navigation("MoteAnstallda");
                });

            modelBuilder.Entity("HR_Dash.Models.RullandeSchema", b =>
                {
                    b.Navigation("Anstallda");
                });
#pragma warning restore 612, 618
        }
    }
}
